# Faster builds https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false
dist: trusty

language: java

jdk:
- openjdk8

before_install:
  - echo "Download Maven 3.6.1....";
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
  - tar xzvf apache-maven-3.6.0-bin.tar.gz
  - export M2_HOME=`pwd`/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -v

script: "mvn clean cobertura:cobertura package"

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2

# After the build, run the script that will collect JaCoCo statistics
# It uses the third-party service https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Send a notification to your email id, if the assembly has dropped
notifications:
  email:
    recipients:
      - singrahu@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
    on_start: never

env:
  global:
    - CODECOV_TOKEN="4a65000e-fadf-4f97-bae1-685522e1df2d"
