# Faster builds https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false
dist: trusty

language: java

jdk:
- openjdk8

matrix:
  include:
    - jdk: openjdk8
      env: CUSTOM_MVN_VERION="3.6.1"

before_install:
  - if [[ -n "${CUSTOM_MVN_VERION}" ]]; then
      echo "Download Maven ${CUSTOM_MVN_VERION}....";
      if [[ "${CUSTOM_MVN_VERION}" == "3.0" ]]; then
        wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.tar.gz || travis_terminate 1;
      else
        wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.tar.gz || travis_terminate 1;
      fi;
      tar xzvf apache-maven-${CUSTOM_MVN_VERION}-bin.tar.gz || travis_terminate 1;
      export M2_HOME=`pwd`/apache-maven-${CUSTOM_MVN_VERION}
      export PATH=$M2_HOME/bin:$PATH
      mvn -v
    fi

script: "mvn clean cobertura:cobertura package"

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2

# After the build, run the script that will collect JaCoCo statistics
# It uses the third-party service https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Send a notification to your email id, if the assembly has dropped
notifications:
  email:
    recipients:
      - singrahu@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
    on_start: never

env:
  global:
    - CODECOV_TOKEN="4a65000e-fadf-4f97-bae1-685522e1df2d"
